apiVersion: v1
kind: ConfigMap
metadata:
  name: influx-config
  namespace: social-network
data:
  InfluxConnStr: "http://autosys:00000000@influxdb.autosys:8086/?db=ingestion"
  InfluxDns: "influxdb.autosys"
  InfluxPort: "8086"
  InfluxDBName: "ingestion"
  InfluxServiceStat: "service_metric"
  InfluxAuth: "autosys:00000000"
  InfluxBatchSize: "10000"