---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: social-network
spec:
  ports:
    - port: 6379
  selector:
    death-star-project: social-network
    app: social-graph-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-redis
      name: social-graph-redis
    spec:
      containers:
        - name: social-graph-redis
          image: simonalphafang/snrd_social_graph:0.0.0
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
