---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-service
  labels:
    death-star-project: social-network
    app: url-shorten-service
  namespace: social-network
spec:
  ports:
    - port: 9090
  selector:
    death-star-project: social-network
    app: url-shorten-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-service
  labels:
    death-star-project: social-network
    app: url-shorten-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: url-shorten-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: url-shorten-service
      name: url-shorten-service
    spec:
      containers:
        - name: url-shorten-service
          image: simonalphafang/social_network:0.1.2
          command: ["UrlShortenService"]
          volumeMounts:
            - mountPath: /social-network-microservices/config/jaeger-config.yml
              subPath: jaeger-config.yml
              name: jaeger-conf-yaml
          env:
            - name: InfluxConnStr
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxConnStr
            - name: InfluxDns
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxDns
            - name: InfluxPort
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxPort
            - name: InfluxDBName
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxDBName
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxServiceStat
            - name: InfluxAuth
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxAuth
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: influx-config
                  key: InfluxBatchSize
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
