---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  ports:
    - port: 27017
  selector:
    death-star-project: social-network
    app: user-timeline-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: user-timeline-mongodb
      name: user-timeline-mongodb
    spec:
      containers:
        - name: user-timeline-mongodb
          image: simonalphafang/snmgo_user_timeline:0.0.0
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
