# image: simonalphafang/socialnetwork-env

FROM yg397/thrift-microservice-deps:xenial

ARG NUM_CPUS=40

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.tar.gz -O /cmake.tgz \
    && tar zvxf /cmake.tgz -C / \
    && rm /usr/bin/cmake \
    && ln -s /cmake-3.22.1-linux-x86_64/bin/cmake /usr/bin/cmake

RUN apt -y install libcurl4-openssl-dev
RUN apt update \
    && apt -y install software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt update \
    && apt -y install gcc-7 g++-7 \
    && cd /usr/bin/ \
    && rm gcc g++ \
    && ln -s gcc-7 gcc \
    && ln -s g++-7 g++

RUN mkdir /influxdb-cxx \
    && git clone https://github.com/awegrzyn/influxdb-cxx.git /influxdb-cxx \
    && cd /influxdb-cxx \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make install

RUN mkdir /redispp \
    && git clone https://github.com/sewenew/redis-plus-plus.git /redispp \
    && cd /redispp \
    && mkdir build \
    && cd build \
    && cmake -DREDIS_PLUS_PLUS_CXX_STANDARD=17 .. \
    && make \
    && make install