apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: frontend
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: frontend
        io.kompose.service: frontend
        role: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: NotIn
                    values:
                      - premium
                    #                  - key: cpufreq
                    #                    operator: In
                    #                    values:
                    #                      - "2.3"

      containers:
        - command:
            - frontend
          image: simonalphafang/hotel_reserve_proto:0.0.10
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-frontend
          ports:
            - containerPort: 5000
            - containerPort: 2112
          resources:
            limits:
              cpu: 300m
              memory: 1.2G
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: InfluxToken
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxToken
            - name: InfluxOrg
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxOrg
            - name: InfluxBucket
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBucket
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBatchSize
            - name: InfluxFlushInterval
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxFlushInterval
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxServiceStat
            - name: InfluxMgoStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMgoStat
            - name: InfluxMemcStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMemcStat


      restartPolicy: Always
status: { }
