apiVersion: v1
kind: ConfigMap
metadata:
  name: svr-geo
data:
  dbconn: "120"
  timeout: "120"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: geo
    io.kompose.service: geo
  name: geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geo
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: geo
        io.kompose.service: geo
        role: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cpufreq
                    operator: In
                    values:
                      - "2.3"
                  - key: disktype
                    operator: NotIn
                    values:
                      - premium
      initContainers:
        - name: db-prob
          image: simonalphafang/alpine-telnet:0.0.1
          command:
            - sh
            - -c
            - "echo \"\" | telnet mongodb-geo 27018"
      containers:
        - command:
            - geo
          image: simonalphafang/hotel_reserve_proto:0.0.10-grace
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-geo
          ports:
            - containerPort: 8083
            - containerPort: 2112
          resources:
            limits:
              cpu: 400m
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: InfluxToken
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxToken
            - name: InfluxOrg
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxOrg
            - name: InfluxBucket
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBucket
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBatchSize
            - name: InfluxFlushInterval
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxFlushInterval
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxServiceStat
            - name: InfluxMgoStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMgoStat
            - name: InfluxMemcStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMemcStat
            - name: SVR_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: svr-geo
                  key: timeout
            - name: SVR_DBCONN
              valueFrom:
                configMapKeyRef:
                  name: svr-geo
                  key: dbconn
      restartPolicy: Always