apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: memc-rate
    io.kompose.service: memc-rate
    role: db
  name: memc-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memc-rate
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        role: db
        app: memc-rate
        io.kompose.service: memc-rate
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: hostType
              labelSelector:
                matchLabels:
                  app: mgo-rate
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostType
                    operator: NotIn
                    values:
                      - monitor
      containers:
        - image: bitnami/memcached
          name: hotel-reserv-rate-memc
          command:
            - "/opt/bitnami/scripts/memcached/run.sh"
          ports:
            - containerPort: 11211
          resources:
            limits:
              cpu: 200m
              memory: 200M
      restartPolicy: Always
