apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-rate
data:
  MEMCACHED_CACHE_SIZE: "128"
  MEMCACHED_THREADS: "2"
  MEMCACHED_CONNECTIONS: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: memcached-rate
    io.kompose.service: memcached-rate
  name: memcached-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached-rate
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        role: db
        app: memcached-rate
        io.kompose.service: memcached-rate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - premium
      containers:
        - env:
            - name: MEMCACHED_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: memcached-rate
                  key: MEMCACHED_CACHE_SIZE
            - name: MEMCACHED_THREADS
              valueFrom:
                configMapKeyRef:
                  name: memcached-rate
                  key: MEMCACHED_THREADS
            - name: MEMCACHED_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: memcached-rate
                  key: MEMCACHED_CONNECTIONS
          image: memcached
          name: hotel-reserv-rate-mmc
          ports:
            - containerPort: 11211
          resources:
            limits:
              cpu: 300m
      restartPolicy: Always
status: { }
