apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-user
data:
  mongo.conf: |
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    net:
      port: 27017
      bindIp: 0.0.0.0

    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: mongodb-user
    io.kompose.service: mongodb-user
  name: mongodb-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        role: db
        app: mongodb-user
        io.kompose.service: mongodb-user
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: NotIn
                    values:
                      - premium
                  - key: cpufreq
                    operator: In
                    values:
                      - "2.6"
      containers:
        - image: mongo
          name: hotel-reserv-user-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 300m
              memory: 1.2G
          args:
            - --config=/tmp/mongodb/mongo.conf
            - --dbpath=/data/db
          volumeMounts:
            #            - mountPath: /data/db
            #              name: user
            - mountPath: /tmp/mongodb
              name: mongodb-conf
      hostname: user-db
      restartPolicy: Always
      volumes:
        #        - name: user
        #          persistentVolumeClaim:
        #            claimName: user-pvc
        - name: mongodb-conf
          configMap:
            name: mongodb-user