apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-reservation
data:
  mongo.conf: |
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    net:
      port: 27017
      bindIp: 0.0.0.0

    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: mongodb-reservation
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-reservation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        role: db
        app: mongodb-reservation
        io.kompose.service: mongodb-reservation
    spec:
      containers:
        - image: mongo
          name: hotel-reserv-reservation-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 350m
          args:
            - --config=/tmp/mongodb/mongo.conf
            - --dbpath=/data/db
          volumeMounts:
            - mountPath: /data/db
              name: reservation
            - mountPath: /tmp/mongodb
              name: mongodb-conf
      hostname: reservation-db
      restartPolicy: Always
      volumes:
        - name: reservation
          persistentVolumeClaim:
            claimName: reservation-pvc
        - name: mongodb-conf
          configMap:
            name: mongodb-reservation