apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-reservation
  labels:
    role: db-config
data:
  mongo.conf: |
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    net:
      port: 27017
      bindIp: 0.0.0.0

    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: mongodb-reservation
    io.kompose.service: mongodb-reservation
    role: db
  name: mongodb-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-reservation
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      labels:
        role: db
        app: mongodb-reservation
        mongoRepl: reserve
        io.kompose.service: mongodb-reservation
    spec:
      serviceAccountName: mgo-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostType
                    operator: NotIn
                    values:
                      - monitor
      containers:
        - image: mongo
          name: hotel-reserv-reservation-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 150m
              memory: 250M
          args:
            - --config=/tmp/mongodb/mongo.conf
          #            - --dbpath=/data/db
          #            - --replSet
          #            - rs0
          #            - --bind_ip_all
          volumeMounts:
            - mountPath: /tmp/mongodb
              name: mongodb-conf
      #        - name: mongo-sidecar
      #          image: cvallance/mongo-k8s-sidecar
      #          env:
      #            - name: "MONGO_SIDECAR_POD_LABELS"
      #              value: "mongoRepl=reserve"
      hostname: reservation-db
      restartPolicy: Always
      volumes:
        - name: mongodb-conf
          configMap:
            name: mongodb-reservation