apiVersion: v1
kind: ServiceAccount
metadata:
  name: mgo-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mgo-operator
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "mgo-op-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mgo-operator
subjects:
  - kind: ServiceAccount
    name: "mgo-operator"
    namespace: default