apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-geo
  labels:
    role: db-config
data:
  mongo.conf: |
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    net:
      port: 27017
      bindIp: 0.0.0.0

    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: mongodb-geo
    io.kompose.service: mongodb-geo
    role: db
  name: mongodb-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-geo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        role: db
        app: mongodb-geo
        io.kompose.service: mongodb-geo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostType
                    operator: NotIn
                    values:
                      - monitor
      containers:
        - image: mongo
          name: hotel-reserv-geo-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 200m
              memory: 250M
          args:
            - --config=/tmp/mongodb/mongo.conf
            - --dbpath=/data/db
          volumeMounts:
            #            - mountPath: /data/db
            #              name: geo
            - mountPath: /tmp/mongodb
              name: mongodb-conf
      restartPolicy: Always
      volumes:
        #        - name: geo
        #          persistentVolumeClaim:
        #            claimName: geo-pvc
        - name: mongodb-conf
          configMap:
            name: mongodb-geo
