apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: profile
    io.kompose.service: profile
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: profile
        io.kompose.service: profile
    spec:
      containers:
        - command:
            - profile
          image: simonalphafang/hotel_reserve_profile:0.0.3-prom
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-profile
          ports:
            - containerPort: 8081
            - containerPort: 2112
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 350m
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
status: { }
