apiVersion: v1
kind: ConfigMap
metadata:
  name: rate
  labels:
    role: server-config
data:
  GOGC: "100"
  GOMAXPROCS: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: rate
    io.kompose.service: rate
    role: server
  name: rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rate
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: rate
        io.kompose.service: rate
        role: server
    spec:
      serviceAccountName: benchop
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: hostType
              labelSelector:
                matchLabels:
                  app: mongodb-rate
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostType
                    operator: NotIn
                    values:
                      - monitor
      initContainers:
        - name: db-probe
          image: simonalphafang/alpine-telnet:0.0.1
          command:
            - sh
            - -c
            - |
              set -ex
              echo '' | telnet mongodb-rate 27017
              echo '' | telnet memcached-rate 11211
      containers:
        - command:
            - rate
          image: simonalphafang/hotel_reserve_proto:0.0.15-nopanic
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-rate
          securityContext:
            privileged: true
          ports:
            - containerPort: 8084
            - containerPort: 2112
          resources:
            limits:
              cpu: 200m
              memory: 100M
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: InfluxToken
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxToken
            - name: InfluxOrg
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxOrg
            - name: InfluxBucket
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBucket
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBatchSize
            - name: InfluxFlushInterval
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxFlushInterval
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxServiceStat
            - name: InfluxMgoStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMgoStat
            - name: InfluxMemcStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMemcStat
            - name: GOGC
              valueFrom:
                configMapKeyRef:
                  key: GOGC
                  name: rate
            - name: GOMAXPROCS
              valueFrom:
                configMapKeyRef:
                  key: GOMAXPROCS
                  name: rate
            - name: SVR_MEMC_TIMEOUT
              value: "1000"
      restartPolicy: Always
