apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: recommendation
    io.kompose.service: recommendation
  name: recommendation
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
    - port: 2112
      name: "2112"
      targetPort: 2112
  selector:
    io.kompose.service: recommendation
status:
  loadBalancer: {}
