apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: recommendation
    io.kompose.service: recommendation
  name: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommendation
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: recommendation
        io.kompose.service: recommendation
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cpufreq
                    operator: In
                    values:
                      - "2.3"
                  - key: disktype
                    operator: NotIn
                    values:
                      - premium
      containers:
        - command:
            - recommendation
          image: simonalphafang/hotel_reserve_proto:0.0.10-test
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-recommendation
          ports:
            - containerPort: 8085
            - containerPort: 2112
          resources:
            limits:
              cpu: 400m
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
status: { }
