apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation
  labels:
    role: server-config
data:
  GOGC: "100"
  GOMAXPROCS: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: recommendation
    io.kompose.service: recommendation
    role: server
  name: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommendation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        app: recommendation
        io.kompose.service: recommendation
        role: server
    spec:
      serviceAccountName: benchop
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: hostType
              labelSelector:
                matchLabels:
                  app: mongodb-recommendation
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hostType
                    operator: NotIn
                    values:
                      - monitor
      containers:
        - command:
            - recommendation
          image: simonalphafang/hotel_reserve_proto:0.0.14-memcscale5
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-recommendation
          securityContext:
            privileged: true
          ports:
            - containerPort: 8085
            - containerPort: 2112
          resources:
            limits:
              cpu: 200m
              memory: 100M
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: InfluxToken
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxToken
            - name: InfluxOrg
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxOrg
            - name: InfluxBucket
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBucket
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBatchSize
            - name: InfluxFlushInterval
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxFlushInterval
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxServiceStat
            - name: InfluxMgoStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMgoStat
            - name: InfluxMemcStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMemcStat

            - name: GOGC
              valueFrom:
                configMapKeyRef:
                  key: GOGC
                  name: recommendation
            - name: GOMAXPROCS
              valueFrom:
                configMapKeyRef:
                  key: GOMAXPROCS
                  name: recommendation
      restartPolicy: Always
