apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  labels:
    role: server-config
data:
  GOGC: "100"
  GOMAXPROCS: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: user
    io.kompose.service: user
    role: server
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      labels:
        app: user
        io.kompose.service: user
        role: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: host_type
                    operator: NotIn
                    values:
                      - monitor
      #                  - key: disktype
      #                    operator: NotIn
      #                    values:
      #                      - premium
      containers:
        - command:
            - user
          image: simonalphafang/hotel_reserve_proto:0.0.11-dbport2
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-user
          ports:
            - containerPort: 8086
            - containerPort: 2112
          resources:
            limits:
              cpu: 200m
              memory: 600M
          env:
            - name: GRPC_GO_REQUIRE_HANDSHAKE
              value: "off"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: InfluxToken
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxToken
            - name: InfluxOrg
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxOrg
            - name: InfluxBucket
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBucket
            - name: InfluxBatchSize
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxBatchSize
            - name: InfluxFlushInterval
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxFlushInterval
            - name: InfluxServiceStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxServiceStat
            - name: InfluxMgoStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMgoStat
            - name: InfluxMemcStat
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: InfluxMemcStat

            - name: GOGC
              valueFrom:
                configMapKeyRef:
                  key: GOGC
                  name: user
            - name: GOMAXPROCS
              valueFrom:
                configMapKeyRef:
                  key: GOMAXPROCS
                  name: user
      restartPolicy: Always
