apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "2112"
  creationTimestamp: null
  labels:
    app: user
    io.kompose.service: user
  name: user
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
    - port: 2112
      name: "2112"
      targetPort: 2112
  selector:
    io.kompose.service: user
status:
  loadBalancer: { }
