apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: {{ .Values.consul.replicas }}
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
        - image: {{ .Values.consul.image }}:{{ .Values.consul.tag }}
          name: consul
          ports:
          {{ - range .Values.consul.ports }}
          {{ with . }}
            - containerPort: {{ .src }}
          {{ end }}
          {{ end }}
              protocol: UDP
          resources:
            requests:
              cpu: {{ .Values.consul.cpuReq }}
            limits:
              cpu: {{ .Values.consul.cpuLimit }}
      restartPolicy: {{ .Values.consul.restart }}
