apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{.Values.appLabel}}: {{.Values.consul.name}}
  name: {{.Values.consul.name}}
spec:
  replicas: {{ .Values.consul.replicas }}
  selector:
    matchLabels:
      {{.Values.appLabel}}: {{.Values.consul.name}}
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      labels:
        {{.Values.appLabel}}: {{.Values.consul.name}}
    spec:
      containers:
        - image: {{ .Values.consul.image }}:{{ .Values.consul.tag }}
          name: {{.Values.consul.image}}
          resources:
          {{- toYaml .Values.consul.rc | nindent 12}}
          ports:
            {{- range .Values.consul.ports }}
            - containerPort: {{ .src }}
              protocol: {{.protocol | default "TCP"}}
      {{- end }}

      restartPolicy: Always
