apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  ports:
  {{- range .Values.ports }}
  {{ with . }}
    - port: {{ .src }}
      targetPort: {{ .dest }}
  {{ end }}
  {{ end }}
      protocol: UDP
  selector:
    io.kompose.service: consul
