apiVersion: v1
kind: Service
metadata:
  labels:
    {{.Values.appLabel}}: {{.Values.consul.name}}
  name: {{.Values.consul.name}}
spec:
  ports:
    {{- range .Values.consul.ports }}
    - port: {{ .src }}
      targetPort: {{ .dest }}
      {{ end }}
      protocol: UDP
  selector:
    {{.Values.appLabel}}: {{.Values.consul.name}}
